### ISSUE TITLE
EADDRNOTAVAIL when using SSL

### ISSUE THREAD

**Issue by editedredx** [greim/hoxy#56]
I'm getting the following error trying to proxy through ssl on **windows**: 
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect EADDRNOTAVAIL
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```
This is my code, http traffic works but whenever I try a https site it error's out.
```javascript
var port = 46769;
var proxy = hoxy.createServer({
    certAuthority: {
        key: fs.readFileSync('f:/ssl/key.pem'),
        cert: fs.readFileSync('f:/ssl/cert.pem')
    }
}).listen(port);

proxy.intercept({
    phase: 'request'
}, function(req, resp, cycle) {
    console.log(123);
});
console.log('tunnel through', port);
```

**Comment by greim** [comment]
Can you try updating to 3.1.1 and re-open if that doesn't solve it?

**Comment by editedredx** [comment]
The error is gone, thanks for the fast response. Https traffic is still not caught though, I've created a new issue for that  #57.
